// Daily couple prompts. Everyone gets the same question and task on the same date, chosen from these lists.
export const dailyQuestions=[
 'What is one small thing I did recently that made you smile?',
 'If we could teleport anywhere for one evening, where would we go?',
 'What song reminds you of us right now?',
 'What was your first impression of me, honestly?',
 'What is a food you want us to try together?',
 'What is one thing you want us to do before this year ends?',
 'When do you feel most loved by me?',
 'What is a memory of us you replay in your head?',
 'What would our perfect lazy Sunday look like?',
 'What is something you have never told me but want to?',
 'Which of my habits secretly makes you happy?',
 'What is one thing you are proud of yourself for this week?',
 'If our relationship was a movie, what would it be called?',
 'What is a tiny tradition you want us to start?',
 'What made you laugh the hardest this week?',
 'Where do you see us one year from today?',
 'What is your favourite photo of us and why?',
 'What is something you want to learn together?',
 'What is one thing that is stressing you out that I can help with?',
 'Describe me in three words today.',
 'What is the best gift you have ever received?',
 'What is one place from your childhood you want to show me?',
 'What would you name our future pet?',
 'What is a compliment you would love to hear more often?',
 'What is your comfort show or movie right now?',
 'If you could relive one day with me, which would it be?',
 'What is one dream you have not said out loud yet?',
 'What is something small I could do tomorrow to make your day better?',
 'What is your favourite thing about the way we talk?',
 'What is the most spontaneous thing you want us to do?',
 'What is a smell that reminds you of me?',
 'Which month of our relationship has been your favourite so far?',
 'What is a rule our future home must have?',
 'What do you think we are really good at as a team?',
 'What is one thing you want me to understand better about you?',
 'What is the silliest argument you remember us having?',
 'What would our couple superpower be?',
 'What is your ideal date night, from start to finish?',
 'What is a skill of mine you wish you had?',
 'What are you most looking forward to this month?',
 'What is one thing you would never change about us?',
 'What is your favourite way to spend time with me without phones?',
 'Which of your friends would get along best with me and why?',
 'What is a country you want us to live in for a month?',
 'What is one worry you want to let go of this week?',
 'What was the moment you knew you really liked me?',
 'What is a song you want played at our wedding?',
 'What is the best advice anyone has given you about love?',
 'What makes you feel safe with me?',
 'What would a surprise from me look like, ideally?',
 'What is a goal you want me to cheer you on for?',
 'What is your favourite thing I cook or order for you?',
 'If we wrote a bucket list tonight, what is item number one?',
 'What is a quote or line that describes us?',
 'What are three things you are grateful for today?',
 'What is one way we have grown since we met?',
 'What would you want our kids or future selves to know about us?',
 'What is the cutest thing I do without realising?',
 'What is something you want more of in our relationship?',
 'What do you love most about today, so far?',
];
export const dailyTasks=[
 'Send each other a voice note, just to say hi.',
 'Share a photo from your day that the other has not seen.',
 'Tell each other one thing you appreciate, out loud or by text.',
 'Plan one tiny thing to look forward to this week.',
 'Send a song that made you think of them.',
 'Compliment something specific about them today.',
 'Share one thing that went well today.',
 'Take a selfie together or send one to each other.',
 'Recommend one reel, video or meme that made you laugh.',
 'Ask how their day really went, and just listen.',
 'Write one line for the journal about today.',
 'Drink a glass of water and remind the other to do it too.',
 'Say good night with something sweet and specific.',
 'Send an old photo of the two of you.',
 'Share one goal for tomorrow with each other.',
 'Do five minutes of something relaxing together, even on call.',
 'Tell them one thing you are looking forward to doing together.',
 'Leave a surprise note or message for them to find.',
 'Share a childhood story they have not heard yet.',
 'Pick a movie or show to watch together soon.',
 'Send a hug emoji at a random moment.',
 'Tell each other one thing that stressed you today.',
 'Share your favourite moment of the week so far.',
 'Plan your next date, even if it is simple.',
 'Send a photo of something that reminded you of them.',
 'Make a wish for each other for tomorrow.',
 'Do one small chore or favour for the other.',
 'Share something new you learned today.',
 'Tell them what you admire about how they handle things.',
 'End the day by sharing one win and one lesson.',
];
const dayNumber=(date:string)=>{const [y,m,d]=date.split('-').map(Number);return Math.floor(Date.UTC(y,m-1,d)/86400000)};
export function promptFor(date:string){const n=dayNumber(date);return {question:dailyQuestions[((n%dailyQuestions.length)+dailyQuestions.length)%dailyQuestions.length],task:dailyTasks[(((n*7+3)%dailyTasks.length)+dailyTasks.length)%dailyTasks.length]}}
