import {z} from 'zod';
import {momentColors} from './tracker';
const short=z.string().max(150), date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/), clock=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const nudge=z.object({enabled:z.boolean(),time:clock});
const file=z.object({id:short,name:short,size:z.number().nonnegative()});
const goal=z.object({id:short.min(1),title:short.min(1),category:short.min(1),color:z.enum(['red','orange','amber','lime','green','teal','cyan','blue','purple','pink']).optional(),description:z.string().max(500),items:z.array(short.min(1)).max(30),target:z.number().positive().max(100000),kind:z.enum(['checkbox','checklist','choice','any','count','duration']),unit:short,essential:z.boolean(),private:z.boolean(),days:z.array(z.number().int().min(0).max(6)).min(1).max(7),reminder:z.union([clock,z.literal('')]),reminders:z.array(z.object({time:clock,item:z.number().int().min(0).max(29).optional()})).max(12).optional(),need:z.number().int().min(1).max(30).optional(),perWeek:z.number().int().min(1).max(7).optional(),easy:z.object({need:z.number().int().min(1).max(30).optional(),target:z.number().positive().max(100000).optional()}).optional(),windows:z.array(z.object({item:z.string().max(150),from:clock,to:clock})).max(30).optional(),sleepPlan:z.object({bedBy:z.union([clock,z.literal('')]),wakeBy:z.union([clock,z.literal('')])}).optional(),archived:z.boolean(),created:date}).refine(g=>g.kind==='checklist'||g.kind==='any'?g.items.length>0:g.kind==='choice'?g.items.length>=2:true);
export const stateSchema=z.object({goals:z.array(goal).max(100),days:z.record(date,z.object({entries:z.array(z.object({goal,checks:z.array(z.boolean()).max(30),value:z.number().min(0).max(100000),note:z.string().max(2000),rest:z.boolean(),exerciseLogs:z.record(z.string().regex(/^(?:[0-9]|[12][0-9])$/),z.object({reps:z.number().int().min(1).max(10000),sets:z.number().int().min(1).max(1000)})).optional(),media:z.array(file).max(12).optional(),easy:z.boolean().optional(),stretch:z.boolean().optional(),resists:z.array(z.number().int().positive()).max(100).optional(),didAt:z.number().int().positive().optional(),times:z.array(clock.nullable()).max(30).optional(),bed:clock.optional(),wake:clock.optional(),noSleep:z.boolean().optional(),couldnt:z.array(z.number().int().min(0).max(29)).max(30).optional()})).max(100),reflection:z.string().max(3000),focus:z.string().max(500),lowEnergy:z.boolean().optional(),energy:z.enum(['full','okay','low']).optional()})),settings:z.object({name:z.string().min(1).max(60),quietStart:clock,quietEnd:clock,reminders:z.boolean(),relationshipStart:z.union([date,z.literal('')]).optional(),allowGoalEdits:z.boolean().optional(),notifyPartner:z.boolean().optional(),hideCouple:z.boolean().optional(),coach:z.boolean().optional(),statColors:z.record(z.string().max(20),z.enum(['rose','amber','blue','purple','green','teal','pink','night'])).optional(),customReminders:z.array(z.object({id:short.min(1),title:z.string().min(1).max(60),emoji:z.string().max(16),time:clock,days:z.array(z.number().int().min(0).max(6)).min(1).max(7),note:z.string().max(120),enabled:z.boolean()})).max(40).optional(),evening:nudge.optional(),dailyNudge:nudge.optional(),timeZone:z.string().max(64).regex(/^[A-Za-z0-9_+\-/]+$/).optional()}),body:z.object({start:z.number().min(20).max(400),target:z.number().min(20).max(400),startDate:date,entries:z.array(z.object({date,kg:z.number().min(20).max(400),weekly:z.boolean().optional()})).max(3000)}).optional(),recaps:z.record(date,z.string().max(1500)).optional(),freezes:z.object({since:date,earned:z.array(z.object({date,reason:z.enum(['month','week'])})).max(2000),used:z.array(date).max(2000)}).optional()});
const comment=z.object({id:short.min(1),author:short,text:z.string().min(1).max(2000),created:z.string().max(40)});
const memory=z.object({id:short.min(1),title:short,body:z.string().max(20000),date,time:z.union([clock,z.literal('')]),location:z.string().max(200),lat:z.number().min(-90).max(90).optional(),lng:z.number().min(-180).max(180).optional(),photos:z.array(file).max(30),author:short,created:z.string().max(40),sensitive:z.boolean().optional(),comments:z.array(comment).max(500).optional(),coverPos:z.object({id:short,x:z.number().min(0).max(100),y:z.number().min(0).max(100)}).optional()});
const moment=z.object({id:short.min(1),title:short.min(1),icon:z.string().min(1).max(16),date,time:z.union([clock,z.literal('')]),color:z.enum(momentColors),repeat:z.literal('yearly').optional()});
const diaryEntry=z.object({id:short.min(1),title:short,body:z.string().min(1).max(100000),date,author:short.min(1),created:z.string().max(40),updated:z.string().max(40)});
// Recently deleted in the journal: one deleted item plus when and by whom.
const journalTrash=z.object({id:short.min(1),kind:z.enum(['memory','milestone','diary','comment']),deletedAt:z.string().max(40),deletedBy:short,memoryId:short.optional(),memory:memory.optional(),milestone:moment.optional(),diary:diaryEntry.optional(),comment:comment.optional()});
const sharedBaseSchema=z.object({journal:z.array(memory).max(3000),moments:z.array(moment).max(100),together:z.union([date,z.literal('')]).optional(),photoDump:z.array(z.object({id:short.min(1),name:short,size:z.number().nonnegative(),sensitive:z.boolean().optional()})).max(5000).optional()});

export const sharedSchema=sharedBaseSchema.extend({photoTrash:z.array(z.object({id:short.min(1),name:short,size:z.number().nonnegative(),sensitive:z.boolean().optional(),deletedAt:z.string().max(40),deletedBy:short,memoryIds:z.array(short).max(100).optional()})).max(5000).optional(),diary:z.array(diaryEntry).max(3000).optional(),journalTrash:z.array(journalTrash).max(3000).optional()});
